import type { CafeCategory, CafeItem } from "@/types/cafe";

export const CAFE_CATEGORIES: CafeCategory[] = [
  { id: "coffee", label: "Coffee" },
  { id: "drinks", label: "Drinks" },
  { id: "snack", label: "Snak" },
];

export const CAFE_ITEMS: CafeItem[] = [
  {
    id: "coffee-freddo-espresso",
    name: "Freddo Espresso",
    description: "Δυνατός, κρύος espresso",
    price: 3.5,
    rating: 4.8,
    image: require("../assets/images/2-2.jpg"),
    categoryId: "coffee",
  },
  {
    id: "coffee-freddo-cappuccino",
    name: "Freddo Cappuccino",
    description: "Κρύος καφές με αφρόγαλα",
    price: 4.0,
    rating: 4.8,
    image: require("../assets/images/3-22.jpg"),
    categoryId: "coffee",
  },
  {
    id: "coffee-espresso",
    name: "Espresso",
    description: "Κλασικός και έντονος",
    price: 2.5,
    rating: 4.7,
    image: require("../assets/images/3-19.jpg"),
    categoryId: "coffee",
  },
  {
    id: "coffee-cappuccino",
    name: "Cappuccino",
    description: "Ζεστός με κρέμα γάλακτος",
    price: 3.0,
    rating: 4.8,
    image: require("../assets/images/3-17.jpg"),
    categoryId: "coffee",
  },
  {
    id: "coffee-lungo",
    name: "Lungo",
    description: "Πιο ήπιος espresso",
    price: 2.8,
    rating: 4.6,
    image: require("../assets/images/5-1.jpg"),
    categoryId: "coffee",
  },
  {
    id: "coffee-frappe",
    name: "Frappe",
    description: "Κλασικός καφές",
    price: 3.0,
    rating: 4.5,
    image: require("../assets/images/3-21.jpg"),
    categoryId: "coffee",
  },
  {
    id: "coffee-nescafe",
    name: "Nes Café",
    description: "Στιγμιαίος καφές",
    price: 2.2,
    rating: 4.4,
    image: require("../assets/images/3-15.jpg"),
    categoryId: "coffee",
  },
  {
    id: "coffee-greek",
    name: "Ελληνικός",
    description: "Παραδοσιακός και δυνατός",
    price: 2.7,
    rating: 4.7,
    image: require("../assets/images/3-14.jpg"),
    categoryId: "coffee",
  },
  {
    id: "coffee-filter",
    name: "Φίλτρου",
    description: "Απολαυστικός",
    price: 3.8,
    rating: 4.6,
    image: require("../assets/images/3-12.jpg"),
    categoryId: "coffee",
  },
  {
    id: "coffee-mocha",
    name: "Mocha",
    description: "Καφές με σοκολάτα",
    price: 4.5,
    rating: 4.8,
    image: require("../assets/images/3-18.jpg"),
    categoryId: "coffee",
  },
  {
    id: "drink-juice-orange",
    name: "Φρέσκος Χυμός",
    description: "Φυσικός, δροσιστικός",
    price: 4.0,
    rating: 4.7,
    image: require("../assets/images/2-1.jpg"),
    categoryId: "drinks",
  },
  {
    id: "drink-lemonade",
    name: "Λεμονάδα Σπιτική",
    description: "Ήπια γλυκόξινη",
    price: 3.8,
    rating: 4.6,
    image: require("../assets/images/3-10.jpg"),
    categoryId: "drinks",
  },
  {
    id: "drink-mixed-juice",
    name: "Ανάμεικτος Χυμός",
    description: "Πορτοκάλι, μήλο, βατόμουρο",
    price: 4.5,
    rating: 4.7,
    image: require("../assets/images/3-16.jpg"),
    categoryId: "drinks",
  },
  {
    id: "drink-iced-tea-lemon",
    name: "Τσάι Λεμόνι",
    description: "Κρύο",
    price: 3.2,
    rating: 4.5,
    image: require("../assets/images/3-23.jpg"),
    categoryId: "drinks",
  },
  {
    id: "drink-iced-tea-peach",
    name: "Τσάι Ροδάκινο",
    description: "Κρύο",
    price: 3.2,
    rating: 4.5,
    image: require("../assets/images/3-23.jpg"),
    categoryId: "drinks",
  },
  {
    id: "drink-hot-tea",
    name: "Τσάι Ζεστό",
    description: "Χαλαρωτικό & απαλό",
    price: 3.0,
    rating: 4.4,
    image: require("../assets/images/3-9.jpg"),
    categoryId: "drinks",
  },
  {
    id: "drink-hot-chocolate",
    name: "Σοκολάτα Ζεστή",
    description: "Πλούσια & κρεμώδης",
    price: 4.2,
    rating: 4.8,
    image: require("../assets/images/3-8.jpg"),
    categoryId: "drinks",
  },
  {
    id: "drink-milkshake",
    name: "Μιλκσέικ",
    description: "Δροσερό & βελούδινο",
    price: 4.8,
    rating: 4.7,
    image: require("../assets/images/3-13.jpg"),
    categoryId: "drinks",
  },
  {
    id: "drink-coca-cola",
    name: "Coca-Cola",
    description: "Κουτάκι",
    price: 2.5,
    rating: 4.3,
    image: require("../assets/images/3-6.jpg"),
    categoryId: "drinks",
  },
  {
    id: "drink-water",
    name: "Νερό Μεσαίο",
    description: "Δροσιστικό & απαραίτητο",
    price: 0.5,
    rating: 4.2,
    image: require("../assets/images/3-7.jpg"),
    categoryId: "drinks",
  },
  {
    id: "snack-croissant",
    name: "Κρουασάν Βουτύρου",
    description: "Αέρινο, κλασικό",
    price: 2.8,
    rating: 4.6,
    image: require("../assets/images/2.jpg"),
    categoryId: "snack",
  },
  {
    id: "snack-sandwich",
    name: "Σάντουιτς",
    description: "Ελαφρύ & νόστιμο",
    price: 4.5,
    rating: 4.6,
    image: require("../assets/images/3-5.jpg"),
    categoryId: "snack",
  },
  {
    id: "snack-bar",
    name: "Μπάρα Δημητριακών",
    description: "Γλυκό & ενεργειακό",
    price: 2.5,
    rating: 4.4,
    image: require("../assets/images/3-4.jpg"),
    categoryId: "snack",
  },
  {
    id: "snack-biscuits",
    name: "Μπισκότα Βρώμης",
    description: "Με μέλι",
    price: 2.2,
    rating: 4.3,
    image: require("../assets/images/3-3.jpg"),
    categoryId: "snack",
  },
  {
    id: "snack-fruit-salad",
    name: "Φρουτοσαλάτα Μικρή",
    description: "Φρέσκα φρούτα",
    price: 3.5,
    rating: 4.6,
    image: require("../assets/images/5.jpg"),
    categoryId: "snack",
  },
  {
    id: "snack-pie",
    name: "Τυροπιτάκια Μερίδα",
    description: "Ζεστά & τραγανά",
    price: 3.8,
    rating: 4.5,
    image: require("../assets/images/3-2.jpg"),
    categoryId: "snack",
  },
  {
    id: "snack-bagel",
    name: "Bagel Γαλοπούλα",
    description: "Απαλό & γεμάτο",
    price: 4.0,
    rating: 4.6,
    image: require("../assets/images/3-1.jpg"),
    categoryId: "snack",
  },
  {
    id: "snack-chips",
    name: "Πατατάκια Crisps",
    description: "Αλμυρό σνακ",
    price: 1.8,
    rating: 4.2,
    image: require("../assets/images/3-20.jpg"),
    categoryId: "snack",
  },
  {
    id: "snack-cake",
    name: "Κέικ ανάμεικτο",
    description: "Αφράτο και φρέσκο",
    price: 3.2,
    rating: 4.5,
    image: require("../assets/images/3.jpg"),
    categoryId: "snack",
  },
  {
    id: "snack-toast",
    name: "Τοστ Γαλοπούλα - Τυρί",
    description: "Ζεστό και χορταστικό",
    price: 3.9,
    rating: 4.6,
    image: require("../assets/images/3-11.jpg"),
    categoryId: "snack",
  },
];
