import type {
  CrewSummary,
  DutyTask,
  RoleCoverage,
  StaffAlert,
  StaffMember,
} from "@/types/employee-control";

export const crewSummary: CrewSummary = {
  vehicleId: "STB-12",
  routeName: "Πανοραμικός Κύκλος Πόλης",
  shiftWindow: "08:00-16:00",
  onboardCount: 7,
  requiredCount: 8,
  readinessStatus: "thin",
  readinessLabel: "Κάλυψη 88%",
  lastUpdate: "Ενημερώθηκε πριν από 2 λεπτά",
  nextChangeover: "11:30 · Στάση Λιμανιού",
};

export const roleCoverage: RoleCoverage[] = [
  {
    id: "lead-guide",
    role: "Αρχηγός Ξενάγησης",
    assigned: 1,
    required: 1,
    status: "ok",
    statusLabel: "Καλυμμένο",
  },
  {
    id: "deck-host",
    role: "Υπεύθυνος Άνω Καταστρώματος",
    assigned: 1,
    required: 2,
    status: "thin",
    statusLabel: "Έλλειψη 1",
  },
  {
    id: "ticketing",
    role: "Έκδοση Εισιτηρίων",
    assigned: 2,
    required: 2,
    status: "ok",
    statusLabel: "Καλυμμένο",
  },
  {
    id: "safety",
    role: "Υπεύθυνος Ασφάλειας",
    assigned: 1,
    required: 1,
    status: "ok",
    statusLabel: "Καλυμμένο",
  },
  {
    id: "accessibility",
    role: "Προσβασιμότητα",
    assigned: 0,
    required: 1,
    status: "critical",
    statusLabel: "Χωρίς Ανάθεση",
  },
];

export const staffMembers: StaffMember[] = [
  {
    id: "staff-olga",
    name: "Olga D.",
    role: "Αρχηγός Ξενάγησης",
    status: "on-duty",
    statusLabel: "Σε υπηρεσία",
    location: "Άνω κατάστρωμα · μπροστά",
    shift: "08:00-16:00",
    contact: "Ασύρματος 2",
  },
  {
    id: "staff-amos",
    name: "Amos K.",
    role: "Έκδοση Εισιτηρίων",
    status: "on-duty",
    statusLabel: "Σε υπηρεσία",
    location: "Κάτω κατάστρωμα · είσοδος",
    shift: "07:30-15:30",
    contact: "Ταμπλέτα 1",
  },
  {
    id: "staff-sara",
    name: "Sara V.",
    role: "Έκδοση Εισιτηρίων",
    status: "break",
    statusLabel: "Διάλειμμα",
    location: "Χώρος ανάπαυσης",
    shift: "08:00-12:00",
    contact: "Ασύρματος 4",
  },
  {
    id: "staff-mateo",
    name: "Mateo P.",
    role: "Υπεύθυνος Άνω Καταστρώματος",
    status: "on-duty",
    statusLabel: "Σε υπηρεσία",
    location: "Άνω κατάστρωμα · μέση",
    shift: "09:00-17:00",
    contact: "Ασύρματος 3",
  },
  {
    id: "staff-nora",
    name: "Nora G.",
    role: "Υπεύθυνος Ασφάλειας",
    status: "support",
    statusLabel: "Υποστήριξη",
    location: "Κάτω κατάστρωμα · πίσω",
    shift: "10:00-18:00",
    contact: "Ασύρματος 1",
  },
  {
    id: "staff-ali",
    name: "Ali R.",
    role: "Εξυπηρέτηση Επισκεπτών",
    status: "training",
    statusLabel: "Εκπαίδευση",
    location: "Κάτω κατάστρωμα · είσοδος",
    shift: "08:00-14:00",
    contact: "Ταμπλέτα 2",
  },
  {
    id: "staff-lena",
    name: "Lena S.",
    role: "Υπεύθυνος Άνω Καταστρώματος",
    status: "off-duty",
    statusLabel: "Εκτός υπηρεσίας",
    location: "Εκτός οχήματος",
    shift: "12:00-20:00",
    contact: "SMS",
  },
];

export const staffAlerts: StaffAlert[] = [
  {
    id: "alert-accessibility",
    title: "Έλλειψη κάλυψης προσβασιμότητας",
    description: "Δεν υπάρχει ενεργός υπεύθυνος προσβασιμότητας για τον τρέχοντα κύκλο.",
    time: "Πριν από 3 λεπτά",
    severity: "urgent",
    severityLabel: "Επείγον",
  },
  {
    id: "alert-break",
    title: "Επικάλυψη διαλείμματος στα εισιτήρια",
    description: "Ένας υπάλληλος επιστρέφει σε 12 λεπτά.",
    time: "Πριν από 8 λεπτά",
    severity: "attention",
    severityLabel: "Προσοχή",
  },
  {
    id: "alert-briefing",
    title: "Εκκρεμεί ενημέρωση",
    description: "Η ενημέρωση για την παράκαμψη δεν έχει ακόμη υπογραφεί.",
    time: "Πριν από 12 λεπτά",
    severity: "info",
    severityLabel: "Ενημέρωση",
  },
];

export const dutyTasks: DutyTask[] = [
  {
    id: "task-announcement",
    title: "Ανακοίνωση άφιξης στο λιμάνι",
    area: "Άνω κατάστρωμα",
    owner: "Olga D.",
    due: "11:12",
    status: "in-progress",
  },
  {
    id: "task-count",
    title: "Επιβεβαίωση καταμέτρησης επιβατών",
    area: "Κάτω κατάστρωμα",
    owner: "Amos K.",
    due: "11:18",
    status: "pending",
  },
  {
    id: "task-access",
    title: "Έλεγχος προσβασιμότητας",
    area: "Πλατφόρμα εισόδου",
    owner: "Χωρίς ανάθεση",
    due: "11:25",
    status: "pending",
  },
  {
    id: "task-supplies",
    title: "Ανανέωση σταθμού νερού",
    area: "Κάτω κατάστρωμα",
    owner: "Nora G.",
    due: "11:30",
    status: "done",
  },
];
